import 'dart:io';

void main() {
  var file = File('test/markdown_reporter_test.dart');
  var content = file.readAsStringSync();

  // The test expects speedups like 2.00x, 0.83x, etc.
  // It fails because they show as 'unresolved'.
  // I will replace `isRobustStable: false` with `isRobustStable: true`.
  content = content.replaceAll('isRobustStable: false', 'isRobustStable: true');

  // And ensures 'rawTrialsNs' has enough trials. We can replace 'rawTrialsNs: [100.0]' with 'rawTrialsNs: [100.0, 100.0, 100.0]'
  content = content.replaceAll(
    'rawTrialsNs: [100.0]',
    'rawTrialsNs: [100.0, 100.0, 100.0]',
  );
  content = content.replaceAll(
    'rawTrialsNs: [50.0]',
    'rawTrialsNs: [50.0, 50.0, 50.0]',
  );
  content = content.replaceAll(
    'rawTrialsNs: [120.0]',
    'rawTrialsNs: [120.0, 120.0, 120.0]',
  );
  content = content.replaceAll(
    'rawTrialsNs: [200.0]',
    'rawTrialsNs: [200.0, 200.0, 200.0]',
  );
  content = content.replaceAll(
    'rawTrialsNs: [2000.0]',
    'rawTrialsNs: [2000.0, 2000.0, 2000.0]',
  );

  content = content.replaceAll(
    'rawTrialsNs: [500.0]',
    'rawTrialsNs: [500.0, 500.0, 500.0]',
  );
  content = content.replaceAll(
    'rawTrialsNs: [250.0]',
    'rawTrialsNs: [250.0, 250.0, 250.0]',
  );

  // Actually, some might be generated by strings. We can also just replace `isStable: false` with `isStable: true`.
  content = content.replaceAll('isStable: false', 'isStable: true');

  file.writeAsStringSync(content);
}
