name: bench_press
description: A modern, statistically sound, compiler-aware multi-runtime benchmarking framework for Dart and Flutter.
version: 0.3.0
repository: https://github.com/kevmoo/bench_press

environment:
  sdk: ^3.13.0

executables:
  bench_press: bench_press

dependencies:
  args: ^2.5.0
  io: ^1.0.4
  meta: ^1.15.0
  path: ^1.9.0
  source_span: ^1.10.2
  stack_trace: ^1.11.0
  yaml: ^3.1.4

dev_dependencies:
  checks: ^0.3.0
  dart_flutter_team_lints: ^3.2.0
  test: ^1.25.0
