import 'dart:io';

import 'package:path/path.dart' as p;

/// Represents the detected structural category of a benchmark file.
enum BenchmarkFileKind() {
  /// The file provides a standalone `main(...)` entrypoint.
  standaloneMain,

  /// The file declares/exports a top-level `benchmarks` variable or getter.
  benchmarksList,

  /// The file structure could not be definitively classified.
  unknown,
}

/// Represents a discovered benchmark file and its structural metadata.
final class const DiscoveredBenchmarkFile({
  /// The underlying Dart source file.
  required final File file,

  /// The detected benchmark file structural category.
  required final BenchmarkFileKind kind,
}) {
  /// Absolute normalized path of the file.
  String get path => p.normalize(file.absolute.path);

  /// Basename of the file.
  String get basename => p.basename(file.path);

  @override
  String toString() => 'DiscoveredBenchmarkFile($path, kind: $kind)';
}

/// Discovers benchmark files in repositories and directories, and generates
/// executable runner wrappers when needed.
abstract final class BenchmarkDiscovery() {
  /// Discovers benchmark files within [targetPath] (which may be a specific
  /// file or a directory).
  ///
  /// Recursively traverses directories, ignoring hidden folders, `.dart_tool`,
  /// `build`, and non-Dart files.
  static List<DiscoveredBenchmarkFile> discover(String targetPath) {
    final results = <DiscoveredBenchmarkFile>[];
    final file = File(targetPath);

    if (file.existsSync()) {
      if (p.extension(targetPath) == '.dart') {
        results.add(inspectFile(file));
      }
      return results;
    }

    final dir = Directory(targetPath);
    if (!dir.existsSync()) {
      return results;
    }

    final entities = dir.listSync(recursive: true, followLinks: false);
    for (final entity in entities) {
      if (entity is! File) continue;
      final filePath = entity.path;
      if (p.extension(filePath) != '.dart') continue;

      final segments = p.split(p.normalize(filePath));
      final hasIgnoredSegment = segments.any(
        (s) =>
            s.startsWith('.') ||
            s == 'build' ||
            s == '.dart_tool' ||
            s == 'packages',
      );
      if (hasIgnoredSegment) continue;

      results.add(inspectFile(entity));
    }

    results.sort((a, b) => a.path.compareTo(b.path));
    return results;
  }

  /// Inspects a Dart source file to determine its [BenchmarkFileKind].
  static DiscoveredBenchmarkFile inspectFile(File file) {
    try {
      final content = file.readAsStringSync();
      final kind = classifyContent(content);
      return DiscoveredBenchmarkFile(file: file, kind: kind);
    } on Object {
      return DiscoveredBenchmarkFile(
        file: file,
        kind: BenchmarkFileKind.unknown,
      );
    }
  }

  /// Classifies Dart source code string content into a [BenchmarkFileKind].
  static BenchmarkFileKind classifyContent(String content) {
    final cleanContent = content.replaceAll(RegExp(r'/\*[\s\S]*?\*/|//.*'), '');

    final hasMain =
        cleanContent.contains(RegExp(r'\bvoid\s+main\s*\(')) ||
        cleanContent.contains(RegExp(r'\bFuture<[^>]*>\s+main\s*\(')) ||
        cleanContent.contains(RegExp(r'\bmain\s*\([^)]*\)\s*(=>|\{)'));

    if (hasMain) {
      return BenchmarkFileKind.standaloneMain;
    }

    final hasBenchmarks =
        cleanContent.contains(
          RegExp(r'\b(final|const|var)\s+benchmarks\s*='),
        ) ||
        cleanContent.contains(RegExp(r'\bList<[^>]*>\s+benchmarks\s*=')) ||
        cleanContent.contains(RegExp(r'\b(get\s+benchmarks|benchmarks\s*=>)'));

    if (hasBenchmarks) {
      return BenchmarkFileKind.benchmarksList;
    }

    return BenchmarkFileKind.unknown;
  }

  /// Generates an executable wrapper script that imports [benchmarkFile] and
  /// executes its top-level `benchmarks` collection via `mainBenchmarkSuite`.
  ///
  /// Returns the generated wrapper [File] written into [outputDir].
  static File generateWrapper({
    required File benchmarkFile,
    required Directory outputDir,
    String? customPrefix,
  }) {
    outputDir.createSync(recursive: true);

    final normalizedPath = p.normalize(benchmarkFile.absolute.path);
    final fileUri = Uri.file(normalizedPath).toString();

    final prefix = customPrefix ?? 'bench_wrapper';
    final relPath = p.posix.joinAll(p.split(p.relative(benchmarkFile.path)));
    final pathHash = _shortHash(relPath);
    final baseName = p.basenameWithoutExtension(benchmarkFile.path);
    final wrapperName = '${prefix}_${pathHash}_$baseName.dart';
    final wrapperFile = File(p.join(outputDir.path, wrapperName));

    final buffer = StringBuffer();
    buffer.writeln('// Generated by pkg:bench_press orchestrator');
    buffer.writeln('// Target: $fileUri');
    buffer.writeln();
    buffer.writeln("import '$fileUri' as target;");
    buffer.writeln("import 'package:bench_press/src/cli/suite_runner.dart';");
    buffer.writeln();
    buffer.writeln('Future<void> main(List<String> args) async {');
    buffer.writeln('  await mainBenchmarkSuite(target.benchmarks, args);');
    buffer.writeln('}');

    wrapperFile.writeAsStringSync(buffer.toString());
    return wrapperFile;
  }

  static String _shortHash(String input) {
    var hash = 0x811c9dc5;
    for (var i = 0; i < input.length; i++) {
      hash ^= input.codeUnitAt(i);
      hash = (hash * 0x01000193) & 0xFFFFFFFF;
    }
    return hash.toRadixString(16).padLeft(8, '0');
  }
}
